url: "https://fän-stuff.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "die ärzte - fän stuff" # the name of your site, e.g. ACME Corp.
